### ISSUE TITLE
Backendless URL Token

### ISSUE THREAD

**Issue by knarz** [aeternity/ae-token-migration-contract#1]
Can the backendless URL https://github.com/aeternity/AETokenBurningProject/blob/master/Burn_listener.js#L20 here be just made accessible for everyone? It seems like with that URL everyone might be able to make POST requests, which might not what we want.

**Comment by dadaphl** [comment]
It used to be like this. Today we changed the default access to read only. Then we created a user with write permissions. Unfortunately `backendless` seems forces us to route all requests through this default access token (the one in the the url), which is now read only. The actual auth token to gain write privileges is part of the request header. This token is temporary and needs to be retrieved by login with username and password. I think its a very poor design of backendless's auth system.

You can see, how we retrieve and use the write token in the `token-burn-listener` 

https://github.com/aeternity/token-burn-listener/blob/master/server.js#L56

**Comment by knarz** [comment]
Danke!
