### ISSUE TITLE
What happens if tokens are sent but there is no data?

### ISSUE THREAD

**Issue by kryztoval** [aeternity/ae-token-migration-contract#3]
https://github.com/aeternity/ae-token-migration-contract/blob/master/contracts/TokenBurner.sol seems to revert() if the address is not included.

doesn't that mean the calling contract is not cancelling properly? since the tokens can't be burnt if there is no address to burn them. 

I am just looking at the (surprisingly common) error of sending AE tokens with no data fields or ak_ address.

**Comment by emil-apeunit** [comment]
@kryztoval The unfortunately common error is that people use the transfer function of the ERC-20 contract, instead of Approve&Call. In these cases our migration contract is not involved and we can also not check for an æternity address.

**Comment by kryztoval** [comment]
@emil-apeunit  sure, but there were some strides in the right direction, like CanReclaimToken and some specific functions to claim funds, but it all needs to be added to the contract at creation, or inherited properly, and if it was not, then the tokens are basically lost.
